### ISSUE TITLE
oauth/authorize 401 Unauthorized

### ISSUE THREAD

**Issue by mohamednizar** [laravel/passport#1133]
- Passport Version: v7.5.1
- Laravel Version: 5.8
- PHP Version: v7.1.32

### Description:
I have been fired this error message after login using passport for authenticate my application.
`{"error":"invalid_client","error_description":"Client authentication failed","message":"Client authentication failed"}`

Found this URL with parameters which are passed: ` http://localhost:3004/oauth/authorize?access_type=online&client_id=2&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin%2Fgeneric_oauth&response_type=code&scope=user%3Aemail&state=taWMGxrAT2l6k1kZXb58bMLewny_la-gC9kv6WXmKsQ%3D`

and perameters are
```
access_type: online
client_id: 2
redirect_uri: http://localhost:3000/login/generic_oauth
response_type: code
scope: user:email
state: taWMGxrAT2l6k1kZXb58bMLewny_la-gC9kv6WXmKsQ=
```

and my request headers 
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Cookie: System=Q2FrZQ%3D%3D.ZWZjYmIxYjA0YmUyYTZkMzcwYmZkY2ZlZTY3Y2I1MTlmODRjN2Q5ZWYwOWJhN2NlZTAxY2YwZWNkNzhkNWQ0Y8CoVUAKf5LzdNbRQDH5B8wTEzyTQM%2F%2BfRoo7cqhvd6yhRnN3VEguTXjKM0GnTub2Q%3D%3D; 5d89dac18813e15aa2f75788275e3588=7q6u32ukce43qpc0ft3813il28; sis_session=eyJpdiI6IlRYa1wvQWg0azlneHFTTjdwUndZekVBPT0iLCJ2YWx1ZSI6InUrakt2WEZCQytpZUxaazJlSW5HMWdiQkFDcHRNdjEzekJiWHdueXRaOSt0SFFmTFhWaHNIaWR6TmpnelhTMUYiLCJtYWMiOiIzOWIzZGYwODhmMTI3YjhmZTJjMjEwZjg1ZDFmMmJhZWI3MTUyMzM3ZTY2YzAwYzNlYmQyYWU0Y2Q1MmMyNmUzIn0%3D; oauth_state=d148457ca1f1151d92e0540b06b03e9db407fac0e1343a4a3e7bd7824efc22bb; XSRF-TOKEN=eyJpdiI6IjFOc3JoMTJldVIyYk9rbGM4MVQ2Z2c9PSIsInZhbHVlIjoiZWdcL2RTbTZYeFo5WkFnWms1XC9za2RndUFoc1NDSEJsaGs0YTN1S1FJalRQY0xpMnZWMFoyMDR0c3Y4SlUwQ0xxIiwibWFjIjoiOGM2YjFjMTZhOWIxNjAzM2JhMDE5NjYwMGZkYWRiZGIxZjBkZDRlYTAyYmJmMWM3MzMyMWFlNjk0YmY1MDM2OSJ9; laravel_session=eyJpdiI6ImZneXZsZ21zMzNrWVF0bDBDdmN1ZWc9PSIsInZhbHVlIjoiOEZ3VVFtS2NuNEZNbFBMQWtUVGdSUVBDUHV2Smhra01cL3hkeWJ0TzhSZTBuREY5ZkdtODBBR0VVUEYyVUp0V0QiLCJtYWMiOiIyYzA3NDNmYWE1YTU1ZTljNTE3YmY3NDFmZjIzZjg3OWE4N2E0NzUyNGZkZTZlMjdhMTljODUyNzEyOWY0ZTc5In0%3D
DNT: 1
Host: localhost:3004
Referer: http://localhost:3004/login
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
```

Found this error log:
```
[2019-12-05 05:49:10] local.ERROR: Client authentication failed {"userId":1,"exception":"[object] (League\\OAuth2\\Server\\Exception\\OAuthServerException(code: 4): Client authentication failed at /app/vendor/league/oauth2-server/src/Exception/OAuthServerException.php:138)
[stacktrace]
#0 /app/vendor/league/oauth2-server/src/Grant/AbstractGrant.php(235): League\\OAuth2\\Server\\Exception\\OAuthServerException::invalidClient()
#1 /app/vendor/league/oauth2-server/src/Grant/AuthCodeGrant.php(254): League\\OAuth2\\Server\\Grant\\AbstractGrant->validateRedirectUri('http://localhos...', Object(Laravel\\Passport\\Bridge\\Client), Object(Zend\\Diactoros\\ServerRequest))
#2 /app/vendor/league/oauth2-server/src/AuthorizationServer.php(157): League\\OAuth2\\Server\\Grant\\AuthCodeGrant->validateAuthorizationRequest(Object(Zend\\Diactoros\\ServerRequest))
#3 /app/vendor/laravel/passport/src/Http/Controllers/AuthorizationController.php(61): League\\OAuth2\\Server\\AuthorizationServer->validateAuthorizationRequest(Object(Zend\\Diactoros\\ServerRequest))
#4 /app/vendor/laravel/passport/src/Http/Controllers/HandlesOAuthErrors.php(28): Laravel\\Passport\\Http\\Controllers\\AuthorizationController->Laravel\\Passport\\Http\\Controllers\\{closure}()
#5 /app/vendor/laravel/passport/src/Http/Controllers/AuthorizationController.php(83): Laravel\\Passport\\Http\\Controllers\\AuthorizationController->withErrorHandling(Object(Closure))
#6 /app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Laravel\\Passport\\Http\\Controllers\\AuthorizationController->authorize(Object(Zend\\Diactoros\\ServerRequest), Object(Illuminate\\Http\\Request), Object(Laravel\\Passport\\ClientRepository), Object(Laravel\\Passport\\TokenRepository))
#7 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Passport\\Http\\Controllers\\AuthorizationController), 'authorize')
#8 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#9 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#10 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /app/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#34 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#35 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#36 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#37 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#38 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#39 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /app/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#56 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#57 /app/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#58 /app/server.php(21): require_once('/app/public/ind...')
#59 {main}
"} 
```

### Steps To Reproduce:
Simply followed the steps given in the Laravel doc and integrate the auth for Grafana UI.I have done more search and invested more than a week to sort this problem. Please give solution for me.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by mohamednizar** [comment]
@driesvints , Thanks in advanced , I have Upgraded!

Passport Version: v8.0
Laravel Version: v6.2
PHP Version: v7.3.11 

Still no luck.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by mohamednizar** [comment]
I have done and dusted. Well, seems no solutions for this. Then I'll move from this. Since It's beginning of the implementation I can find a best which is working for me.

**Comment by Sephster** [comment]
Looking at the strack trace, I think you have an issue with your redirect URI. It seems it hasn't been registered against the client.
