### ISSUE TITLE
BC Break, 7.5 -> 8.3, laminas-diactoros?

### ISSUE THREAD

**Issue by derekrprice** [laravel/passport#1179]
- Passport Version: 8.3.1
- Laravel Version: 6.9.0
- PHP Version: 7.4.0
- Database Driver & Version: MySQL

### Description:
After upgrading from passport 7.5.1 -> 8.3.1, with no other changes, a client token request crashes with this error:
```
device-service-fpm_1    | [2020-02-03 13:56:30] local.ERROR: Return value of Zend\Diactoros\normalizeServer() must be of the type array, none returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of Zend\\Diactoros\
device-service-fpm_1    | ormalizeServer() must be of the type array, none returned at /var/www/device-service/vendor/laminas/laminas-diactoros/src/functions/normalize_server.legacy.php:22)
device-service-fpm_1    | [stacktrace]
device-service-fpm_1    | #0 /var/www/device-service/vendor/symfony/psr-http-message-bridge/Factory/DiactorosFactory.php(52): Zend\\Diactoros\
device-service-fpm_1    | ormalizeServer()
device-service-fpm_1    | #1 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(131): Symfony\\Bridge\\PsrHttpMessage\\Factory\\DiactorosFactory->createRequest()
device-service-fpm_1    | #2 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}()
device-service-fpm_1    | #3 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()
device-service-fpm_1    | #4 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve()
device-service-fpm_1    | #5 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\\Container\\Container->make()
device-service-fpm_1    | #6 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(79): Illuminate\\Foundation\\Application->make()
device-service-fpm_1    | #7 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(46): Illuminate\\Routing\\ControllerDispatcher->transformDependency()
device-service-fpm_1    | #8 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(27): Illuminate\\Routing\\ControllerDispatcher->resolveMethodDependencies()
device-service-fpm_1    | #9 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(41): Illuminate\\Routing\\ControllerDispatcher->resolveClassMethodDependencies()
device-service-fpm_1    | #10 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
device-service-fpm_1    | #11 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
device-service-fpm_1    | #12 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
device-service-fpm_1    | #13 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
device-service-fpm_1    | #14 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
device-service-fpm_1    | #15 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
device-service-fpm_1    | #16 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
device-service-fpm_1    | #17 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
device-service-fpm_1    | #18 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
device-service-fpm_1    | #19 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
device-service-fpm_1    | #20 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
device-service-fpm_1    | #21 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
device-service-fpm_1    | #22 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
device-service-fpm_1    | #23 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
device-service-fpm_1    | #24 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
device-service-fpm_1    | #25 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
device-service-fpm_1    | #26 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
device-service-fpm_1    | #27 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
device-service-fpm_1    | #28 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
device-service-fpm_1    | #29 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
device-service-fpm_1    | #30 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
device-service-fpm_1    | #31 /var/www/device-service/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
device-service-fpm_1    | #32 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
device-service-fpm_1    | #33 /var/www/device-service/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
device-service-fpm_1    | #34 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle()
device-service-fpm_1    | #35 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
device-service-fpm_1    | #36 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
device-service-fpm_1    | #37 /var/www/device-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
device-service-fpm_1    | #38 /var/www/device-service/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
device-service-fpm_1    | #39 {main}
device-service-fpm_1    | "}
```
### Steps To Reproduce:
1. Upgrade laravel/passport to 8.3.1.
1. Make an /oauth/token request using a client token. **_Request fails._**
1. Revert laravel/passport to 7.5.1.
1. Repeat same token request.  **_Request succeeds._**

**Comment by driesvints** [comment]
Please open an issue on the laminas repo.

**Comment by derekrprice** [comment]
Opened laminas/laminas-diactoros#34.

**Comment by driesvints** [comment]
It's best that you reformat the message to point out the BC break in laminas. Otherwise you'll issue will get closed as they'll think it being a passport issue.

**Comment by derekrprice** [comment]
I'm not sure how to do that.  The first line in the stack trace is coming out of a third party package complaining about expecting a different return value from a laminas method.  I wasn't even sure I should blame laminas and not passport or even a new version of the third party package.  That is why I opened the ticket here in the first place.
