### ISSUE TITLE
Expectations Fails with actingAsClient

### ISSUE THREAD

**Issue by iBotPeaches** [laravel/passport#1338]
- Passport Version: 9.3.2
- Laravel Version: 7.26.1
- PHP Version: 7.4.3
- Database Driver & Version: Maria 10.2.x

### Description:
I was doing an upgrade to 7.x, this endpoint continues to function for real live smoke tests, but our automated tests fail. I've double checked readme's and can't track this down. I don't have control over the `actingAsClient` and I think I've made the test as simple as possible.

### Steps To Reproduce:

Basic test (example)
```
        Passport::actingAsClient($client);

        $response = $this->postJson('/oauth/token', [
            'grant_type' => 'client_credentials',
            'client_id' => $client->getKey(),
            'client_secret' => $client->secret,
            'scope' => '*',
        ]);
```

Returns
```
[2020-09-01 21:13:04] testing.ERROR: Received Mockery_1_Laravel_Passport_TokenRepository::create(), but no expectations were specified {"exception":"[object] (Mockery\\Exception\\BadMethodCallException(code: 0): Received Mockery_1_Laravel_Passport_TokenRepository::create(), but no expectations were specified at /code/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code:915)
[stacktrace]
#0 /code/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code(964): Mockery_1_Laravel_Passport_TokenRepository->_mockery_handleMethodCall('create', Array)
#1 /code/vendor/laravel/passport/src/Bridge/AccessTokenRepository.php(65): Mockery_1_Laravel_Passport_TokenRepository->create(Array)
#2 /code/vendor/league/oauth2-server/src/Grant/AbstractGrant.php(442): Laravel\\Passport\\Bridge\\AccessTokenRepository->persistNewAccessToken(Object(Laravel\\Passport\\Bridge\\AccessToken))
#3 /code/vendor/league/oauth2-server/src/Grant/ClientCredentialsGrant.php(52): League\\OAuth2\\Server\\Grant\\AbstractGrant->issueAccessToken(Object(DateInterval), Object(Laravel\\Passport\\Bridge\\Client), NULL, Array)
#4 /code/vendor/league/oauth2-server/src/AuthorizationServer.php(198): League\\OAuth2\\Server\\Grant\\ClientCredentialsGrant->respondToAccessTokenRequest(Object(Nyholm\\Psr7\\ServerRequest), Object(League\\OAuth2\\Server\\ResponseTypes\\BearerTokenResponse), Object(DateInterval))
#5 /code/vendor/laravel/passport/src/Http/Controllers/AccessTokenController.php(63): League\\OAuth2\\Server\\AuthorizationServer->respondToAccessTokenRequest(Object(Nyholm\\Psr7\\ServerRequest), Object(Laminas\\Diactoros\\Response))
#6 /code/vendor/laravel/passport/src/Http/Controllers/HandlesOAuthErrors.php(24): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->Laravel\\Passport\\Http\\Controllers\\{closure}()
#7 /code/vendor/laravel/passport/src/Http/Controllers/AccessTokenController.php(65): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->withErrorHandling(Object(Closure))
```

Run against Postman without tests.
```
{
    "token_type": "Bearer",
    "expires_in": 31536000,
    "access_token": "[redacated]"
}
```

Relevant testing versions
---

```
            "name": "mockery/mockery",
            "version": "1.3.3",
```

```
            "name": "phpunit/phpunit",
            "version": "8.5.8",
```

**Comment by iBotPeaches** [comment]
This was dumb. It took a night to click. Why am I mocking out the client when testing a method that generates the token?

Putting up a PR for a non-related spacing fix. Sorry about this.
