### ISSUE TITLE
OAuthServerException on publishing to Socket.io over Redis

### ISSUE THREAD

**Issue by amirmasoud** [laravel/passport#300]
I'm trying to establish a io connectino with Laravel-Echo-Server over Redis DB, I get the following error while the event that should broadcast is fired:

```

  
[2017-02-28 18:38:51] local.INFO: Broadcasting [App\Events\UserRegistered] on channels [mychan] with payload:
{
    "user": {
        "id": 44,
        "uuid": "2644e020-fde5-11e6-b8b9-6d73b83042ec",
        "email": "client_5_2644e020-fde5-11e6-b8b9-6d73b83042ec@example.com",
        "phone": "5",
        "role": "client",
        "social_id": null,
        "login_by": "manual",
        "verified": false,
        "created_at": "2017-02-28 18:38:51",
        "updated_at": "2017-02-28 18:38:51"
    },
    "socket": null
}  
[2017-02-28 18:38:51] local.ERROR: League\OAuth2\Server\Exception\OAuthServerException: The resource owner or authorization server denied the request. in /vendor/league/oauth2-server/src/Exception/OAuthServerException.php:165
Stack trace:
#0 /vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(66): League\OAuth2\Server\Exception\OAuthServerException::accessDenied('Access token ha...')
#1 /vendor/league/oauth2-server/src/ResourceServer.php(82): League\OAuth2\Server\AuthorizationValidators\BearerTokenValidator->validateAuthorization(Object(Zend\Diactoros\ServerRequest))
#2 /vendor/laravel/passport/src/Guards/TokenGuard.php(110): League\OAuth2\Server\ResourceServer->validateAuthenticatedRequest(Object(Zend\Diactoros\ServerRequest))
#3 /vendor/laravel/passport/src/Guards/TokenGuard.php(90): Laravel\Passport\Guards\TokenGuard->authenticateViaBearerToken(Object(Illuminate\Http\Request))
#4 /vendor/laravel/passport/src/PassportServiceProvider.php(251): Laravel\Passport\Guards\TokenGuard->user(Object(Illuminate\Http\Request))
#5 [internal function]: Laravel\Passport\PassportServiceProvider->Laravel\Passport\{closure}(Object(Illuminate\Http\Request))
#6 /vendor/laravel/framework/src/Illuminate/Auth/RequestGuard.php(54): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 /vendor/barryvdh/laravel-debugbar/src/DataCollector/MultiAuthCollector.php(68): Illuminate\Auth\RequestGuard->user()
#8 /vendor/barryvdh/laravel-debugbar/src/DataCollector/MultiAuthCollector.php(35): Barryvdh\Debugbar\DataCollector\MultiAuthCollector->resolveUser(Object(Illuminate\Auth\RequestGuard))
#9 /vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php(678): Barryvdh\Debugbar\DataCollector\MultiAuthCollector->collect()
#10 /vendor/maximebf/debugbar/src/DebugBar/DebugBar.php(246): Barryvdh\Debugbar\LaravelDebugbar->collect()
#11 /vendor/maximebf/debugbar/src/DebugBar/DebugBar.php(302): DebugBar\DebugBar->getData()
#12 /vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php(591): DebugBar\DebugBar->sendDataInHeaders(true)
#13 /vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(60): Barryvdh\Debugbar\LaravelDebugbar->modifyResponse(Object(Illuminate\Http\Request), Object(Illuminate\Http\JsonResponse))
#14 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#28 /public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#29 /server.php(21): require_once('/Applications/M...')
#30 {main}  


```

on the other hand when I change the auth gaurd in the `config/auth.php` file, the error will change to:

```

[2017-02-28 15:59:49] local.ERROR: Debugbar exception: Auth guard driver [api] is not defined.  

```

the client side of Echo is fine, and laravel-echo-server is just working fine. How can I solve this problem?

Laravel version: 5.4.13
PHP version: 7.1.1

**Comment by amirmasoud** [comment]
Just needed to open the issue to solve the problem. 🙈  I was mistakely sending the Authorization header along the way.
