### ISSUE TITLE
Artisan::call('passport:client') not working while running from controller

### ISSUE THREAD

**Issue by bbdangar** [laravel/passport#439]
`passport:client` not working while calling from controller
I am trying to run this in controller
`$cleint = Artisan::call('passport:client');`
It gives exception 
`{
    "message": "There are no commands defined in the \"passport\" namespace.",
    "status_code": 500,
    "debug": {
        "line": 533,
        "file": "/home/bbdangar/public_html/mik_lab/macca-madina/vendor/symfony/console/Application.php",
        "class": "Symfony\\Component\\Console\\Exception\\CommandNotFoundException",
        "trace": [
            "#0 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/symfony/console/Application.php(565): Symfony\\Component\\Console\\Application->findNamespace('passport')",
            "#1 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/symfony/console/Application.php(204): Symfony\\Component\\Console\\Application->find('passport:client')",
            "#2 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/symfony/console/Application.php(130): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))",
            "#3 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Console/Application.php(141): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))",
            "#4 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(221): Illuminate\\Console\\Application->call('passport:client', Object(Illuminate\\Support\\Collection), NULL)",
            "#5 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Foundation\\Console\\Kernel->call('passport:client')",
            "#6 /home/bbdangar/public_html/mik_lab/macca-madina/app/Http/Controllers/Api/AuthController.php(59): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)",
            "#7 [internal function]: App\\Http\\Controllers\\Api\\AuthController->registerDevice(Object(Dingo\\Api\\Http\\Request))",
            "#8 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)",
            "#9 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\\Routing\\Controller->callAction('registerDevice', Array)",
            "#10 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Api\\AuthController), 'registerDevice')",
            "#11 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\\Routing\\Route->runController()",
            "#12 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Routing/Router.php(559): Illuminate\\Routing\\Route->run()",
            "#13 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#14 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#15 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#16 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#17 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#18 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#19 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))",
            "#20 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
            "#21 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/dingo/api/src/Routing/Adapter/Laravel.php(81): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#22 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/dingo/api/src/Routing/Router.php(513): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
            "#23 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#24 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#25 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#26 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\\Debugbar\\Middleware\\Debugbar->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#27 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#28 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#29 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#30 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#31 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#32 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#33 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#34 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#35 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#36 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#37 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
            "#38 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#39 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#40 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#41 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#42 /home/bbdangar/public_html/mik_lab/macca-madina/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
            "#43 /home/bbdangar/public_html/mik_lab/macca-madina/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
            "#44 {main}"
        ]
    }
}`

**Comment by ViktorLalev** [comment]
Probably should add the following in your Console/Kernal.php
``protected $commands = [
        'Laravel\Passport\Console\ClientCommand'
    ];``
