### ISSUE TITLE
Using Passport  with JWT in Cookie

### ISSUE THREAD

**Issue by sadnub** [laravel/passport#963]
Hello,
I have been really struggling with this concept. I am trying to move to a purely API authenticated approach. I have Laravel on the Backend with VueJS. I am also using a single graphql enpoint for all communications.

So I am trying to mimic the CreateFreshApiTokens Middleware by creating a login method like this:

```
     /**
     * Create a new middleware instance.
     *
     * @param  \Laravel\Passport\ApiTokenCookieFactory  $cookieFactory
     * @return void
     */
    public function __construct(ApiTokenCookieFactory $cookieFactory)
    {
        $this->cookieFactory = $cookieFactory;
    }

    /**
     * @param $rootValue
     * @param array $args
     * @param \Nuwave\Lighthouse\Support\Contracts\GraphQLContext|null $context
     * @param \GraphQL\Type\Definition\ResolveInfo $resolveInfo
     * @return array
     * @throws \Exception
     */
    public function resolve($rootValue, array $args, GraphQLContext $context = null, ResolveInfo $resolveInfo)
    {
        
        if (!Auth::attempt(['email' => $args['data']['username'], 'password' => $args['data']['password']])) {

          throw new AuthenticationException('Authentication Failed');
        }

        Cookie::queue($this->cookieFactory->make(
                Auth::user()->getKey(), $context->request->cookie('XSRF-TOKEN')
            )
        );

        return true;
    }
```
This works for the most part. The user is authenticated. The Cookie gets returned, but I still get 401 errors when accessing the API. Here are the cookies on I am getting:

![image](https://user-images.githubusercontent.com/20450757/52918506-e1d09480-32c5-11e9-8b70-441c47d9996d.png)

I am using auth:api middleware on the endpoint. Is there anything else I could be missing? 

Thanks!

**Comment by sadnub** [comment]
So it looks like the token can't be decoded from the cookie

```
[2019-02-18 01:01:35] local.DEBUG: Exception Details: Illuminate\Contracts\Encryption\DecryptException: The payload is invalid. in /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:191
Stack trace:
#0 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(134): Illuminate\Encryption\Encrypter->getJsonPayload(NULL)
#1 /var/www/laravel-tenancy-passport-demo/vendor/laravel/passport/src/Guards/TokenGuard.php(258): Illuminate\Encryption\Encrypter->decrypt('eyJ0eXAiOiJKV1Q...', false)
#2 /var/www/laravel-tenancy-passport-demo/vendor/laravel/passport/src/Guards/TokenGuard.php(228): Laravel\Passport\Guards\TokenGuard->decodeJwtTokenCookie(Object(Illuminate\Http\Request))
#3 /var/www/laravel-tenancy-passport-demo/vendor/laravel/passport/src/Guards/TokenGuard.php(200): Laravel\Passport\Guards\TokenGuard->getTokenViaCookie(Object(Illuminate\Http\Request))
#4 /var/www/laravel-tenancy-passport-demo/vendor/laravel/passport/src/Guards/TokenGuard.php(97): Laravel\Passport\Guards\TokenGuard->authenticateViaCookie(Object(Illuminate\Http\Request))
#5 /var/www/laravel-tenancy-passport-demo/vendor/laravel/passport/src/PassportServiceProvider.php(274): Laravel\Passport\Guards\TokenGuard->user(Object(Illuminate\Http\Request))
#6 [internal function]: Laravel\Passport\PassportServiceProvider->Laravel\Passport\{closure}(Object(Illuminate\Http\Request), NULL)
#7 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Auth/RequestGuard.php(58): call_user_func(Object(Closure), Object(Illuminate\Http\Request), NULL)
#8 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(60): Illuminate\Auth\RequestGuard->user()
#9 /var/www/laravel-tenancy-passport-demo/app/GraphQL/Directives/ProtectDirective.php(162): Illuminate\Auth\RequestGuard->check()
#10 /var/www/laravel-tenancy-passport-demo/app/GraphQL/Directives/ProtectDirective.php(74): App\GraphQL\Directives\ProtectDirective->authenticate(Object(Illuminate\Http\Request), Array)
#11 /var/www/laravel-tenancy-passport-demo/vendor/webonyx/graphql-php/src/Executor/Executor.php(781): App\GraphQL\Directives\ProtectDirective->App\GraphQL\Directives\{closure}(NULL, Array, Object(Nuwave\Lighthouse\Schema\Context), Object(GraphQL\Type\Definition\ResolveInfo))
#12 /var/www/laravel-tenancy-passport-demo/vendor/webonyx/graphql-php/src/Executor/Executor.php(744): GraphQL\Executor\Executor->resolveOrError(Object(GraphQL\Type\Definition\FieldDefinition), Object(GraphQL\Language\AST\FieldNode), Object(Closure), NULL, Object(Nuwave\Lighthouse\Schema\Context), Object(GraphQL\Type\Definition\ResolveInfo))
#13 /var/www/laravel-tenancy-passport-demo/vendor/webonyx/graphql-php/src/Executor/Executor.php(473): GraphQL\Executor\Executor->resolveField(Object(GraphQL\Type\Definition\ObjectType), NULL, Object(ArrayObject), Array)
#14 /var/www/laravel-tenancy-passport-demo/vendor/webonyx/graphql-php/src/Executor/Executor.php(349): GraphQL\Executor\Executor->executeFields(Object(GraphQL\Type\Definition\ObjectType), NULL, Array, Object(ArrayObject))
#15 /var/www/laravel-tenancy-passport-demo/vendor/webonyx/graphql-php/src/Executor/Executor.php(309): GraphQL\Executor\Executor->executeOperation(Object(GraphQL\Language\AST\OperationDefinitionNode), NULL)
#16 /var/www/laravel-tenancy-passport-demo/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromiseAdapter.php(59): GraphQL\Executor\Executor->GraphQL\Executor\{closure}(Array, Array)
#17 /var/www/laravel-tenancy-passport-demo/vendor/webonyx/graphql-php/src/Executor/Executor.php(310): GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter->create(Object(Closure))
#18 /var/www/laravel-tenancy-passport-demo/vendor/webonyx/graphql-php/src/Executor/Executor.php(166): GraphQL\Executor\Executor->doExecute()
#19 /var/www/laravel-tenancy-passport-demo/vendor/webonyx/graphql-php/src/GraphQL.php(155): GraphQL\Executor\Executor::promiseToExecute(Object(GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter), Object(GraphQL\Type\Schema), Object(GraphQL\Language\AST\DocumentNode), NULL, Object(Nuwave\Lighthouse\Schema\Context), Array, 'getTickets', NULL)
#20 /var/www/laravel-tenancy-passport-demo/vendor/webonyx/graphql-php/src/GraphQL.php(86): GraphQL\GraphQL::promiseToExecute(Object(GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter), Object(GraphQL\Type\Schema), 'query getTicket...', NULL, Object(Nuwave\Lighthouse\Schema\Context), Array, 'getTickets', NULL, Array)
#21 /var/www/laravel-tenancy-passport-demo/vendor/nuwave/lighthouse/src/GraphQL.php(113): GraphQL\GraphQL::executeQuery(Object(GraphQL\Type\Schema), 'query getTicket...', NULL, Object(Nuwave\Lighthouse\Schema\Context), Array, 'getTickets', NULL, Array)
#22 /var/www/laravel-tenancy-passport-demo/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php(83): Nuwave\Lighthouse\GraphQL->executeQuery('query getTicket...', Object(Nuwave\Lighthouse\Schema\Context), Array)
#23 /var/www/laravel-tenancy-passport-demo/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php(62): Nuwave\Lighthouse\Support\Http\Controllers\GraphQLController->execute(Object(Illuminate\Http\Request))
#24 [internal function]: Nuwave\Lighthouse\Support\Http\Controllers\GraphQLController->query(Object(Illuminate\Http\Request))
#25 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#26 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('query', Array)
#27 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Nuwave\Lighthouse\Support\Http\Controllers\GraphQLController), 'query')
#28 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#29 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Routing\Route->run()
#30 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), 60, '1')
#39 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#43 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#44 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#45 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#46 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/laravel-tenancy-passport-demo/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/laravel-tenancy-passport-demo/vendor/hyn/multi-tenant/src/Middleware/EagerIdentification.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Hyn\Tenancy\Middleware\EagerIdentification->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/laravel-tenancy-passport-demo/vendor/hyn/multi-tenant/src/Middleware/HostnameActions.php(76): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Hyn\Tenancy\Middleware\HostnameActions->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 /var/www/laravel-tenancy-passport-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#71 /var/www/laravel-tenancy-passport-demo/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#72 {main}  
```

**Comment by driesvints** [comment]
Hi there,

Looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)
